export const produtos = [
  {
    id: "1acb",
    nome: "Bolo chocolate",
    descricao: "cobertura chocolate e granulado",
    tempo: 10,
    preco: 4.5,
    imagem: "https://picsum.photos/id/167/500/300",
    icon: "fas fa-cheese",
    categoria: "Bolo",
  },
  {
    id: "5ahy",
    nome: "Bolo pão de mel",
    descricao: "cobertura de brigadeiro gourmet",
    tempo: 7,
    preco: 5,
    imagem: "https://picsum.photos/id/27/500/300",
    icon: "fas fa-cheese",
    categoria: "Bolo",
  },
  {
    id: "8mhr",
    nome: "Bolo de Amêndoas",
    descricao: "Recheios de trufados",
    tempo: 10,
    preco: 7.25,
    imagem: "https://picsum.photos/id/39/500/300",
    icon: "fas fa-cheese",
    categoria: "Bolo",
  },
  {
    id: "2lio",
    nome: "Pizza calabresa",
    descricao: "Mussarela, calabresa, cebola e oregano",
    tempo: 30,
    preco: 32.7,
    imagem: "https://picsum.photos/id/47/500/300",
    icon: "fas fa-pizza-slice",
    categoria: "Pizza",
  },
  {
    id: "9zdt",
    nome: "Pizza nordestina",
    descricao: "Carne de sol, azeite, orégano e azeitonas",
    tempo: 30,
    preco: 35.5,
    imagem: "https://picsum.photos/id/546/500/300",
    icon: "fas fa-pizza-slice",
    categoria: "Pizza",
  },
  {
    id: "4efg",
    nome: "Hambúrguer Angus quarter",
    descricao: "Pão, quiejo e blend angus",
    tempo: 12,
    preco: 18,
    imagem: "https://picsum.photos/id/689/500/300",
    icon: "fas fa-hamburger",
    categoria: "Hambúrguer",
  },
  {
    id: "3ahj",
    nome: "Hambúrguer Angus Salad",
    descricao: "Pão, presunto e cebola roxa",
    tempo: 15,
    preco: 13.2,
    imagem: "https://picsum.photos/id/75/500/300",
    icon: "fas fa-hamburger",
    categoria: "Hambúrguer",
  },
  {
    id: "7qpr",
    nome: "Hambúrguer Angus bacon",
    descricao: "Pão, bacon e queijo",
    tempo: 17,
    preco: 20.9,
    imagem: "https://picsum.photos/id/898/500/300",
    icon: "fas fa-hamburger",
    categoria: "Hambúrguer",
  },
  {
    id: "6djc",
    nome: "Peixe empanado",
    descricao: "Pimenta e suco de limão",
    tempo: 40,
    preco: 58,
    imagem: "https://picsum.photos/id/94/500/300",
    icon: "fas fa-fish",
    categoria: "Peixe",
  },
  {
    id: "5kht",
    nome: "Bacalhau gratinado",
    descricao: "creme de mandioca e queijo ralado",
    tempo: 38,
    preco: 65,
    imagem: "https://picsum.photos/id/109/500/300",
    icon: "fas fa-fish",
    categoria: "Peixe",
  },
  {
    id: "3rty",
    nome: "Maça de chocolate",
    descricao: "Coco, confete e granulado ",
    tempo: 5,
    preco: 3.25,
    imagem: "https://picsum.photos/id/113/500/300",
    icon: "fas fa-apple-alt",
    categoria: "Frutas",
  },
  {
    id: "7sgt",
    nome: "Banana empanada",
    descricao: "Leite condensado e canela",
    tempo: 7,
    preco: 4.5,
    imagem: "https://picsum.photos/id/124/500/300",
    icon: "fas fa-apple-alt",
    categoria: "Frutas",
  },
  {
    id: "2mnb",
    nome: "Cachorro quente da vovô",
    descricao: "Milho e batata palha",
    tempo: 5,
    preco: 2.5,
    imagem: "https://picsum.photos/id/313/500/300",
    icon: "fas fa-hotdog",
    categoria: "Cachorro Quente",
  },
  {
    id: "7sgt",
    nome: "Cachorro Quente com Creme de Leite",
    descricao: "Molho de tomate, catchup e maionese",
    tempo: 5,
    preco: 2.5,
    imagem: "https://picsum.photos/id/149/500/300",
    icon: "fas fa-hotdog",
    categoria: "Cachorro Quente",
  },
];
